<h1>Listar de Usuário</h1>
<table class="table table-striped table-hover">
    <thead class="thead-dark">
    <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Foto</th>
        <th>Cpf</th>
        <th>Ações</th>
    </tr>
    </thead>
    <tbody>
        <?php
        foreach ($users as $user) {
            echo "
            <tr>
                <td>{$user->getName()}</td>
                <td>{$user->getEmail()}</td>
                <td>{$user->getImage()}</td>
                <td>{$user->getCpf()}</td>
                <td>
                    <a href='#' class='btn btn-warning btn-sm'>Editar</a>    
                    <a href='/usuario/excluir?id={$user->getId()}' class='btn btn-danger btn-sm'>Excluir</a>    
                </td>
            </tr>
            ";
            }

        ?>
    </tbody>
</table>